
  .this is unexpected output!
  ────────────────────────────────────────────────────────────────────────────  
   RISKY  Tests\Fixtures\UnexpectedOutput > output                              
  This test printed output: this is unexpected output

  at src/Support/StateGenerator.php:58
     54▕             foreach ($riskyEvents as $riskyEvent) {
     55▕                 $state->add(TestResult::fromPestParallelTestCase(
     56▕                     $riskyEvent->test(),
     57▕                     TestResult::RISKY,
  ➜  58▕                     ThrowableBuilder::from(new TestOutcome($riskyEvent->message()))
     59▕                 ));
     60▕             }
     61▕         }
     62▕

  1   src/Support/StateGenerator.php:58
      +5 vendor frames 
  7   src/Plugins/Actions/CallsHandleArguments.php:29


  Tests:    1 risky, 1 passed (2 assertions)